### PR TITLE
Add website

### PR DESCRIPTION
**Pull request by MatthewScholefield**
There's no issues tab so I had to create a PR. I'd like to share your fork, but the linked GitHub pages isn't running:

https://luckydonald-forks.github.io/fsm/

Would you mind enabling it? Thanks!

### CODE REVIEW

**Comment by MatthewScholefield** [comment]
@luckydonald Ping

**Comment by luckydonald** [comment]
Technically this isn't meant to be hosted, I think.
I don't even know what to do here.

**Comment by MatthewScholefield** [comment]
What do you mean exactly? The repo has a modification to a website for making FSMs so I assumed it'd make sense to use GitHub pages to host it.

I temporarily made a fork to do this: https://matthewscholefield.github.io/fsm/

If you're not familiar with GitHub Pages, just run `python3 build.py` to update `fsm.js` and then push a new `gh-pages` branch with the change, making sure GitHub Pages is enabled in the repo settings.

**Comment by luckydonald** [comment]
I'm not sure, but can you make a pull request for a non-existing branch?

**Comment by MatthewScholefield** [comment]
Unfortunately, no. You can perform the commands yourself and then just close this PR. The commands would be as follows:

```bash
git clone https://github.com/luckydonald-forks/fsm
cd fsm
git checkout -b gh-pages
python3 build.py
git add fsm.js
git commit -m "Update generated page"
git push -u origin gh-pages
```

Then you just need to [enable GitHub Pages in the repo settings](https://guides.github.com/features/pages/).

**Comment by luckydonald** [comment]
I think it is working now. 
Thanks for the detailed walkthrough!

**Comment by luckydonald** [comment]
Are those changes in e6d8a0a still relevant?

**Comment by MatthewScholefield** [comment]
Sweet, it's working now. Yeah, they are still relevant, but I don't feel like getting them fixed for a PR (I have to make the edits in the src javascript file since I stupidly edited the compiled version).

**Pull request closed without merging**
